from __future__ import annotations

import html
import json
import os
import re
import shutil
import socket
import subprocess
import time
import urllib.error
import urllib.request
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Iterable

import psutil
from django.conf import settings


@dataclass
class ArtifactDraft:
    name: str
    language: str
    content: str
    file_type: str = "text"
    disk_path: str = ""


@dataclass
class ResponseDraft:
    content: str
    thinking: str = ""
    files: list[ArtifactDraft] = field(default_factory=list)
    test_passed: bool | None = None
    test_output: str = ""

    @property
    def tokens(self) -> int:
        return max(1, len(self.content.split()) + sum(len(f.content.split()) for f in self.files))


def safe_filename(value: str, fallback: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "_", value).strip("._")
    return cleaned[:80] or fallback


def wants_image(prompt: str) -> bool:
    text = prompt.lower()
    markers = ["/imagine", "создай карт", "сгенерируй карт", "нарисуй", "image", "photo", "picture"]
    return any(marker in text for marker in markers)


def wants_file(prompt: str) -> bool:
    text = prompt.lower()
    markers = [
        "создай файл",
        "сгенерируй файл",
        "write file",
        "create file",
        "напиши код",
        "generate code",
        ".py",
        ".ts",
        ".tsx",
        ".js",
        ".html",
        ".css",
    ]
    return any(marker in text for marker in markers)


def infer_file(prompt: str) -> tuple[str, str]:
    text = prompt.lower()
    explicit = re.search(r"([\w.-]+\.(py|tsx|ts|js|html|css|json|md|txt))", prompt, re.IGNORECASE)
    if explicit:
        name = safe_filename(explicit.group(1), "generated.txt")
        ext = name.rsplit(".", 1)[-1].lower()
    elif "react" in text or "next" in text or "tsx" in text:
        name, ext = "GeneratedWidget.tsx", "tsx"
    elif "html" in text or "сайт" in text:
        name, ext = "index.html", "html"
    elif "css" in text or "style" in text:
        name, ext = "styles.css", "css"
    elif "javascript" in text or "node" in text:
        name, ext = "script.js", "js"
    elif "markdown" in text or "readme" in text:
        name, ext = "README.md", "md"
    else:
        name, ext = "generated_task.py", "py"

    language = {
        "py": "python",
        "tsx": "tsx",
        "ts": "typescript",
        "js": "javascript",
        "html": "html",
        "css": "css",
        "json": "json",
        "md": "markdown",
        "txt": "text",
    }.get(ext, "text")
    return name, language


def language_from_filename(filename: str, fallback: str = "text") -> str:
    ext = filename.rsplit(".", 1)[-1].lower() if "." in filename else ""
    return {
        "py": "python",
        "tsx": "tsx",
        "ts": "typescript",
        "js": "javascript",
        "html": "html",
        "css": "css",
        "json": "json",
        "md": "markdown",
        "txt": "text",
        "yml": "yaml",
        "yaml": "yaml",
        "sh": "bash",
    }.get(ext, fallback)


def artifact_protocol_prompt() -> str:
    return """You can create real workspace files when that is the right way to satisfy the user.
Decide yourself whether the user needs normal chat text or one or more files.
When the user asks for code, a project, files, "send it as files", or an implementation that is better delivered as files, use this workflow:

1. Write a very short implementation plan in normal chat text.
2. Output every needed file as a complete file block.
3. Finish with a short summary of what was created and what should be tested.

File blocks must use this exact format:

```ttd-file path="relative/path.ext"
full file content here
```

Rules:
- Use safe relative paths only.
- Do not use absolute paths.
- Do not omit file content.
- Do not put commentary inside file blocks.
- If multiple files are needed, output multiple ttd-file blocks.
- Keep explanation outside file blocks short.
- For normal chat answers, do not output ttd-file blocks.
- Do not mention the ttd-file protocol to the user.
"""


def _safe_generated_relative_path(value: str, fallback: str) -> str:
    cleaned = value.strip().strip("\"'` ")
    cleaned = cleaned.replace("\\", "/").lstrip("/")
    parts = [safe_filename(part, "") for part in cleaned.split("/") if part and part not in {".", ".."}]
    result = "/".join(part for part in parts if part)
    return result or fallback


def generated_dir(kind: str) -> Path:
    path = Path(settings.TTD_GENERATED_DIR) / kind
    path.mkdir(parents=True, exist_ok=True)
    return path


def build_code(prompt: str, name: str, language: str) -> str:
    title = prompt.strip()[:120] or "Generated task"
    if language == "python":
        return f'''"""
Generated by Time To Deny.
Task: {title}
"""


def solve(input_text: str = "") -> str:
    """Return a deterministic response for the requested task."""
    cleaned = input_text.strip()
    if not cleaned:
        return "TTD generated file is ready."
    return f"Processed: {{cleaned}}"


def main() -> None:
    print(solve())


if __name__ == "__main__":
    main()
'''
    if language in {"typescript", "tsx"}:
        return """import React from 'react';

type Props = {
  title?: string;
};

export default function GeneratedWidget({ title = 'Time To Deny' }: Props) {
  return (
    <section className="rounded border border-cyan-400/30 bg-black p-4 text-cyan-100">
      <h2 className="text-sm font-bold tracking-wider">{title}</h2>
      <p className="mt-2 text-xs text-cyan-200/80">
        Generated component scaffold. Wire real data through props before shipping.
      </p>
    </section>
  );
}
"""
    if language == "javascript":
        return """export function runTask(input = '') {
  const value = String(input).trim();
  return value ? `Processed: ${value}` : 'TTD generated file is ready.';
}

console.log(runTask(process.argv.slice(2).join(' ')));
"""
    if language == "html":
        escaped = html.escape(title)
        return f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Time To Deny Generated Page</title>
    <style>
      body {{ margin: 0; background: #050607; color: #d7fff2; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }}
      main {{ min-height: 100vh; display: grid; place-items: center; padding: 24px; }}
      section {{ border: 1px solid rgba(0, 255, 136, .35); padding: 24px; max-width: 720px; }}
    </style>
  </head>
  <body>
    <main>
      <section>
        <h1>Time To Deny</h1>
        <p>{escaped}</p>
      </section>
    </main>
  </body>
</html>
"""
    if language == "css":
        return """:root {
  color-scheme: dark;
  --ttd-bg: #050607;
  --ttd-text: #d7fff2;
  --ttd-accent: #00ff88;
}

.ttd-generated {
  background: var(--ttd-bg);
  color: var(--ttd-text);
  border: 1px solid color-mix(in srgb, var(--ttd-accent), transparent 60%);
  padding: 1rem;
}
"""
    return f"Generated file for task:\n{title}\n"


def test_generated_file(path: Path, language: str) -> tuple[bool, str]:
    if language == "python":
        env = os.environ.copy()
        env["PYTHONDONTWRITEBYTECODE"] = "1"
        proc = subprocess.run(
            ["python3", "-B", "-m", "py_compile", str(path)],
            capture_output=True,
            env=env,
            text=True,
            timeout=20,
        )
        pycache = path.parent / "__pycache__"
        if pycache.exists():
            shutil.rmtree(pycache, ignore_errors=True)
        if proc.returncode == 0:
            return True, "python -m py_compile: OK"
        return False, (proc.stderr or proc.stdout or "py_compile failed").strip()

    if language in {"javascript", "typescript", "tsx"}:
        return True, "Static generation OK. Runtime test skipped because Node.js is optional for backend tests."

    if language == "html":
        content = path.read_text(encoding="utf-8")
        passed = "<html" in content.lower() and "</html>" in content.lower()
        return passed, "HTML smoke check: OK" if passed else "HTML smoke check failed"

    return True, "File write smoke check: OK"


def create_code_artifact(prompt: str, chat_id: str | None = None) -> tuple[ArtifactDraft, bool, str]:
    name, language = infer_file(prompt)
    content = build_code(prompt, name, language)
    if chat_id:
        from .workspaces import write_workspace_file

        disk_path = write_workspace_file(chat_id, name, content)
    else:
        disk_name = f"{uuid.uuid4().hex}_{safe_filename(name, 'generated.txt')}"
        disk_path = generated_dir("files") / disk_name
    disk_path.write_text(content, encoding="utf-8")
    passed, output = test_generated_file(disk_path, language)
    return ArtifactDraft(name=name, language=language, content=content, file_type="code", disk_path=str(disk_path)), passed, output


def create_model_file_artifacts(
    prompt: str,
    response: str,
    chat_id: str,
    *,
    allow_fallback: bool = False,
) -> tuple[list[ArtifactDraft], bool | None, str, str]:
    from .workspaces import write_workspace_file

    artifacts: list[ArtifactDraft] = []
    test_outputs: list[str] = []
    passed_values: list[bool] = []
    consumed_ranges: list[tuple[int, int]] = []

    explicit_pattern = re.compile(
        r"```(?:ttd-file|file)\s+(?:path=)?[\"']?(?P<path>[^\"'\n`]+)[\"']?\s*\n(?P<content>.*?)```",
        re.IGNORECASE | re.DOTALL,
    )
    for match in explicit_pattern.finditer(response):
        raw_path = match.group("path")
        content = match.group("content").strip("\n")
        if not content.strip():
            continue
        relative_path = _safe_generated_relative_path(raw_path, infer_file(prompt)[0])
        language = language_from_filename(relative_path)
        disk_path = write_workspace_file(chat_id, relative_path, content)
        passed, output = test_generated_file(disk_path, language)
        artifacts.append(ArtifactDraft(name=relative_path, language=language, content=content, file_type="code", disk_path=str(disk_path)))
        passed_values.append(passed)
        test_outputs.append(f"{relative_path}: {output}")
        consumed_ranges.append(match.span())

    if allow_fallback and not artifacts:
        code_pattern = re.compile(r"```(?P<language>[A-Za-z0-9_+.-]*)\s*\n(?P<content>.*?)```", re.DOTALL)
        match = code_pattern.search(response)
        if match:
            fallback_name, fallback_language = infer_file(prompt)
            content = match.group("content").strip("\n")
            language = language_from_filename(fallback_name, match.group("language") or fallback_language)
            disk_path = write_workspace_file(chat_id, fallback_name, content)
            passed, output = test_generated_file(disk_path, language)
            artifacts.append(ArtifactDraft(name=fallback_name, language=language, content=content, file_type="code", disk_path=str(disk_path)))
            passed_values.append(passed)
            test_outputs.append(f"{fallback_name}: {output}")
            consumed_ranges.append(match.span())

    if allow_fallback and not artifacts and response.strip():
        fallback_name, fallback_language = infer_file(prompt)
        content = response.strip()
        disk_path = write_workspace_file(chat_id, fallback_name, content)
        passed, output = test_generated_file(disk_path, fallback_language)
        artifacts.append(ArtifactDraft(name=fallback_name, language=fallback_language, content=content, file_type="code", disk_path=str(disk_path)))
        passed_values.append(passed)
        test_outputs.append(f"{fallback_name}: {output}")

    cleaned_response = response
    for start, end in reversed(consumed_ranges):
        cleaned_response = f"{cleaned_response[:start]}{cleaned_response[end:]}"
    cleaned_response = cleaned_response.strip()
    if artifacts:
        file_list = ", ".join(f"`{artifact.name}`" for artifact in artifacts)
        cleaned_response = f"Создал файл(ы): {file_list}." + (f"\n\n{cleaned_response}" if cleaned_response else "")

    aggregate_passed = all(passed_values) if passed_values else None
    return artifacts, aggregate_passed, "\n".join(test_outputs), cleaned_response


def create_image_artifact(prompt: str, public_url: str) -> ArtifactDraft:
    image_prompt = prompt.replace("/imagine", "", 1).strip() or "Time To Deny generated image"
    safe_prompt = html.escape(image_prompt[:220])
    disk_name = f"{uuid.uuid4().hex}_ttd_image.svg"
    disk_path = generated_dir("images") / disk_name
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="640" viewBox="0 0 1024 640">
  <defs>
    <linearGradient id="bg" x1="0" x2="1" y1="0" y2="1">
      <stop offset="0" stop-color="#050607"/>
      <stop offset="0.48" stop-color="#071f22"/>
      <stop offset="1" stop-color="#170b24"/>
    </linearGradient>
    <filter id="glow"><feGaussianBlur stdDeviation="6" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
  </defs>
  <rect width="1024" height="640" fill="url(#bg)"/>
  <g opacity="0.28">
    <path d="M0 120 H1024 M0 220 H1024 M0 320 H1024 M0 420 H1024 M0 520 H1024" stroke="#00ff88"/>
    <path d="M128 0 V640 M256 0 V640 M384 0 V640 M512 0 V640 M640 0 V640 M768 0 V640 M896 0 V640" stroke="#00ccff"/>
  </g>
  <circle cx="740" cy="210" r="130" fill="#aa88ff" opacity="0.18" filter="url(#glow)"/>
  <circle cx="300" cy="380" r="170" fill="#00ff88" opacity="0.12" filter="url(#glow)"/>
  <text x="64" y="96" fill="#00ff88" font-family="monospace" font-size="34" font-weight="700">TIME TO DENY</text>
  <text x="64" y="148" fill="#d7fff2" font-family="monospace" font-size="20">generated image placeholder</text>
  <foreignObject x="64" y="210" width="880" height="260">
    <div xmlns="http://www.w3.org/1999/xhtml" style="font: 28px monospace; color: #d7fff2; line-height: 1.35;">
      {safe_prompt}
    </div>
  </foreignObject>
</svg>
"""
    disk_path.write_text(svg, encoding="utf-8")
    return ArtifactDraft(name="ttd_generated_image.svg", language="svg", content=f"{public_url}{disk_name}", file_type="image_url", disk_path=str(disk_path))


def mock_text_response(prompt: str, mode: str, model_name: str, attachment_count: int = 0) -> str:
    attachment_line = ""
    if attachment_count:
        attachment_line = f"\n\nЯ получил вложения: {attachment_count}. Их содержимое сохранено вместе с сообщением."
    mode_line = "Expert mode включен: отвечаю подробнее и с проверками." if mode == "expert" else "Instant mode: коротко и по делу."
    return (
        f"{mode_line}\n\n"
        f"Модель `{model_name}` приняла запрос и backend реально записал его в базу. "
        "Если подключить `TTD_MODEL_BACKEND=llamacpp`, этот же поток пойдет через локальный `llama-server`. "
        "Сейчас mock-backend закрывает интерфейс, хранение, стриминг и служебные действия без ожидания тяжелых весов."
        f"{attachment_line}\n\n"
        f"Запрос: {prompt.strip() or '[empty]'}"
    )


def build_local_draft(
    prompt: str,
    mode: str,
    model_name: str,
    public_image_base: str,
    attachment_count: int = 0,
    chat_id: str | None = None,
) -> ResponseDraft:
    thinking = ""
    if mode == "expert":
        thinking = "Analyzing request...\nChecking whether files or images are needed...\nPreparing persistent artifacts and tests..."

    if wants_image(prompt):
        file = create_image_artifact(prompt, public_image_base)
        return ResponseDraft(
            content="Сгенерировал изображение и приложил его к ответу.",
            thinking=thinking,
            files=[file],
            test_passed=True,
            test_output="Image artifact written to media/generated/images",
        )

    if wants_file(prompt):
        file, passed, output = create_code_artifact(prompt, chat_id=chat_id)
        return ResponseDraft(
            content=f"Создал файл `{file.name}`. Содержимое показано ниже, тест/проверка уже выполнены.",
            thinking=thinking,
            files=[file],
            test_passed=passed,
            test_output=output,
        )

    return ResponseDraft(content=mock_text_response(prompt, mode, model_name, attachment_count), thinking=thinking)


def chunk_text(text: str, size: int = 16) -> Iterable[str]:
    for idx in range(0, len(text), size):
        yield text[idx : idx + size]


def likely_russian(text: str) -> bool:
    cyrillic = sum(1 for char in text if "а" <= char.lower() <= "я" or char.lower() == "ё")
    return cyrillic >= 2


def language_guard(prompt: str) -> str:
    if likely_russian(prompt):
        return (
            "The latest user message is Russian. Answer in Russian only, unless the user explicitly asks for another "
            "language. Do not output unrelated transliterated words, Malay, Indonesian, Turkish, Lezgian, or filler."
        )
    return "Answer in the same language as the latest user message."


def looks_like_language_drift(prompt: str, response: str) -> bool:
    if not likely_russian(prompt):
        return False
    stripped = response.strip()
    if len(stripped) < 12:
        return False
    if "```" in stripped:
        return False
    cyrillic = sum(1 for char in stripped if "а" <= char.lower() <= "я" or char.lower() == "ё")
    latin = sum(1 for char in stripped if "a" <= char.lower() <= "z")
    return cyrillic == 0 and latin >= 6


def llama_cpp_system_prompt(mode: str, system_prompt: str = "", latest_prompt: str = "") -> str:
    system = system_prompt.strip() or (
        "You are Time To Deny, a local AI assistant powered by llama.cpp. "
        "Answer clearly, stream useful output, and prefer runnable code when asked. "
        "Always answer in the same language as the user's latest message. "
        "If the user writes in Russian, answer in Russian. "
        "Never switch to Indonesian, Malay, Turkish, or another unrelated language unless the user asks for it."
    )
    if mode == "expert":
        system += "\nUse careful reasoning internally, then provide a direct final answer."
    else:
        system += "\nAnswer directly and keep latency low."
    if latest_prompt:
        system += f"\n{language_guard(latest_prompt)}"
    system += f"\n{artifact_protocol_prompt()}"
    return system


def token_from_llamacpp_chunk(item: dict) -> str:
    choices = item.get("choices")
    if isinstance(choices, list) and choices:
        first = choices[0] if isinstance(choices[0], dict) else {}
        delta = first.get("delta")
        if isinstance(delta, dict):
            return str(delta.get("content") or "")
        message = first.get("message")
        if isinstance(message, dict):
            return str(message.get("content") or "")
        return str(first.get("text") or "")
    return str(item.get("content") or item.get("response") or "")


def is_llamacpp_done(item: dict) -> bool:
    if item.get("stop") or item.get("done"):
        return True
    choices = item.get("choices")
    if isinstance(choices, list) and choices:
        first = choices[0] if isinstance(choices[0], dict) else {}
        return bool(first.get("finish_reason"))
    return False


def normalize_history(history: list[dict[str, str]] | None) -> list[dict[str, str]]:
    if not history:
        return []
    normalized: list[dict[str, str]] = []
    for item in history[-settings.TTD_CHAT_CONTEXT_MESSAGES :]:
        role = item.get("role", "")
        content = (item.get("content") or "").strip()
        if role not in {"user", "assistant"} or not content:
            continue
        normalized.append({"role": role, "content": content[:4000]})
    return normalized


def _llamacpp_payload(
    prompt: str,
    mode: str,
    model_name: str,
    system_prompt: str = "",
    history: list[dict[str, str]] | None = None,
    extra_guard: str = "",
) -> dict:
    system = llama_cpp_system_prompt(mode, system_prompt, prompt)
    if extra_guard:
        system += f"\n{extra_guard}"
    payload = {
        "model": model_name,
        "messages": [
            {"role": "system", "content": system},
            *normalize_history(history),
            {"role": "user", "content": prompt.strip()},
        ],
        "stream": True,
        "temperature": 0.12 if mode == "expert" else 0.18,
        "top_p": 0.88,
    }
    if settings.TTD_LLAMA_CPP_N_PREDICT > 0:
        payload["max_tokens"] = settings.TTD_LLAMA_CPP_N_PREDICT
    return payload


def _iter_llamacpp_tokens(payload: dict, stop_checker: Callable[[], None] | None = None) -> Iterable[str]:
    req = urllib.request.Request(
        f"{settings.TTD_LLAMA_CPP_URL.rstrip('/')}/v1/chat/completions",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    deadline = time.monotonic() + settings.TTD_LLAMA_READY_TIMEOUT_SECONDS
    last_error: Exception | None = None

    while time.monotonic() <= deadline:
        try:
            with urllib.request.urlopen(req, timeout=settings.TTD_REQUEST_TIMEOUT_SECONDS) as response:
                for raw in response:
                    if stop_checker:
                        stop_checker()
                    if not raw:
                        continue
                    line = raw.decode("utf-8").strip()
                    if not line or line.startswith(":"):
                        continue
                    if line.startswith("data:"):
                        line = line[5:].strip()
                    if line == "[DONE]":
                        return
                    item = json.loads(line)
                    token = token_from_llamacpp_chunk(item)
                    if token:
                        yield token
                    if is_llamacpp_done(item):
                        return
                return
        except urllib.error.HTTPError as exc:
            last_error = exc
            if exc.code != 503 or time.monotonic() >= deadline:
                break
            if stop_checker:
                stop_checker()
            time.sleep(2)
        except (TimeoutError, socket.timeout) as exc:
            last_error = exc
            break
        except (urllib.error.URLError, json.JSONDecodeError) as exc:
            last_error = exc
            break

    if isinstance(last_error, urllib.error.HTTPError) and last_error.code == 503:
        raise RuntimeError(
            "llama.cpp model is still not ready after waiting. It is usually still loading, out of RAM/VRAM, "
            "or crashed during model load. Check Admin -> Server Load -> runtime logs or run ./linux.sh logs."
        ) from last_error
    if isinstance(last_error, (TimeoutError, socket.timeout)):
        raise RuntimeError(
            f"llama.cpp did not produce a token within {settings.TTD_REQUEST_TIMEOUT_SECONDS}s. "
            "The model is too slow for the current server/context, still loading, or stuck. "
            "Try again, reduce LLAMA_CPP_CTX_SIZE, use a smaller quant/model, or increase TTD_REQUEST_TIMEOUT_SECONDS."
        ) from last_error

    raise RuntimeError(
        f"llama.cpp backend unavailable: {last_error}. Start llama-server or switch TTD_MODEL_BACKEND=mock for UI-only dev."
    ) from last_error


def stream_llamacpp(
    prompt: str,
    mode: str,
    model_name: str,
    system_prompt: str = "",
    history: list[dict[str, str]] | None = None,
    stop_checker: Callable[[], None] | None = None,
) -> Iterable[str]:
    payload = _llamacpp_payload(prompt, mode, model_name, system_prompt, history)
    token_iter = _iter_llamacpp_tokens(payload, stop_checker=stop_checker)
    initial_tokens: list[str] = []
    initial_text = ""

    for token in token_iter:
        initial_tokens.append(token)
        initial_text += token
        if len(initial_text.strip()) >= 80 or len(initial_tokens) >= 8:
            break

    if looks_like_language_drift(prompt, initial_text):
        retry_payload = _llamacpp_payload(
            prompt,
            mode,
            model_name,
            system_prompt,
            history,
            "Previous answer drifted into the wrong language. Retry once and answer in clean Russian only.",
        )
        token_iter = _iter_llamacpp_tokens(retry_payload, stop_checker=stop_checker)
        initial_tokens = []
        for token in token_iter:
            initial_tokens.append(token)
            if len("".join(initial_tokens).strip()) >= 80 or len(initial_tokens) >= 8:
                break

    for token in initial_tokens:
        if stop_checker:
            stop_checker()
        yield token

    for token in token_iter:
        if stop_checker:
            stop_checker()
        yield token


def system_snapshot(interval: str) -> dict:
    cpu = psutil.cpu_percent(interval=0.1)
    mem = psutil.virtual_memory()
    current = {
        "cpu": round(cpu, 1),
        "ram": round(mem.percent, 1),
        "gpu": 0,
        "vram": 0,
        "temp": 0,
        "fanRpm": 0,
        "totalVram": "-",
        "usedVram": "-",
        "totalRam": f"{mem.total / (1024 ** 3):.1f}GB",
        "usedRam": f"{mem.used / (1024 ** 3):.1f}GB",
    }

    points = {"1min": 60, "30min": 30, "1hr": 60, "1day": 24, "1week": 7}.get(interval, 30)
    data = []
    for i in range(points):
        wave = (i % 10) * 1.7
        data.append(
            {
                "t": label_for_interval(interval, i),
                "cpu": max(0, min(100, cpu + wave - 8)),
                "ram": max(0, min(100, mem.percent + (i % 7) - 3)),
                "gpu": 0,
                "vram": 0,
                "tps": max(0, min(80, 12 + (i % 12) * 2.5)),
            }
        )

    processes = []
    for proc in psutil.process_iter(["pid", "name", "cpu_percent", "num_threads", "create_time"]):
        try:
            name = proc.info.get("name") or ""
            lowered = name.lower()
            if not any(marker in lowered for marker in ["python", "llama", "node", "next"]):
                continue
            uptime = max(0, time.time() - float(proc.info.get("create_time") or time.time()))
            processes.append(
                {
                    "id": f"proc-{proc.info['pid']}",
                    "name": name,
                    "pid": proc.info["pid"],
                    "status": "active",
                    "vram": "-",
                    "cpu": f"{proc.info.get('cpu_percent') or 0:.1f}%",
                    "threads": proc.info.get("num_threads") or 0,
                    "uptime": format_uptime(uptime),
                }
            )
        except (psutil.NoSuchProcess, psutil.AccessDenied, ValueError):
            continue

    return {"current": current, "history": data, "processes": processes[:24], "system": system_info()}


def label_for_interval(interval: str, index: int) -> str:
    if interval == "1min":
        return f"{index}s"
    if interval in {"30min", "1hr"}:
        return f"{index}m"
    if interval == "1day":
        return f"{index}:00"
    return ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"][index % 7]


def format_uptime(seconds: float) -> str:
    minutes = int(seconds // 60)
    hours = minutes // 60
    minutes = minutes % 60
    if hours:
        return f"{hours}h {minutes}m"
    return f"{minutes}m"


def system_info() -> list[dict[str, str]]:
    mem = psutil.virtual_memory()
    return [
        {"label": "CPU", "value": os.uname().machine if hasattr(os, "uname") else "unknown"},
        {"label": "RAM", "value": f"{mem.total / (1024 ** 3):.1f}GB"},
        {"label": "Python", "value": os.sys.version.split()[0]},
        {"label": "Model backend", "value": settings.TTD_MODEL_BACKEND},
        {"label": "llama.cpp URL", "value": settings.TTD_LLAMA_CPP_URL},
        {"label": "Model dir", "value": str(settings.TTD_MODEL_DIR)},
    ]


def infer_hf_model_type(repo_id: str, tags: list[str], pipeline_tag: str | None = None) -> str:
    haystack = " ".join([repo_id, *tags, pipeline_tag or ""]).lower()
    code_markers = ("coder", "code", "programming", "fill-mask-code")
    vision_markers = ("vision", "image", "diffusion", "stable-diffusion", "sdxl", "flux", "clip", "siglip")

    if any(marker in haystack for marker in code_markers):
        return "code"
    if any(marker in haystack for marker in vision_markers):
        return "vision"
    return "text"


def search_huggingface_models(query: str, model_type: str = "", limit: int = 8) -> list[dict[str, Any]]:
    try:
        from huggingface_hub import HfApi
    except ImportError as exc:
        raise RuntimeError("huggingface_hub is not installed on the backend") from exc

    api = HfApi()
    normalized_query = (query or "").strip()
    normalized_type = model_type if model_type in {"text", "vision", "code"} else ""
    fetch_limit = max(limit * 5, 24)
    seen: set[str] = set()
    results: list[dict[str, Any]] = []
    search_term = f"{normalized_query} GGUF".strip() if normalized_query else "gguf"

    try:
        iterator = api.list_models(search=search_term, limit=fetch_limit)
        for item in iterator:
            repo_id = getattr(item, "id", None) or getattr(item, "modelId", None)
            if not repo_id or repo_id in seen:
                continue
            seen.add(repo_id)

            try:
                details = api.model_info(repo_id)
            except Exception:
                continue

            siblings = getattr(details, "siblings", None) or []
            gguf_files = sorted(
                {
                    getattr(file, "rfilename", "")
                    for file in siblings
                    if getattr(file, "rfilename", "").lower().endswith(".gguf")
                }
            )
            if not gguf_files:
                continue

            tags = list(getattr(details, "tags", None) or getattr(item, "tags", None) or [])
            pipeline_tag = getattr(details, "pipeline_tag", None) or getattr(item, "pipeline_tag", None)
            inferred_type = infer_hf_model_type(repo_id, tags, pipeline_tag)
            if normalized_type and inferred_type != normalized_type:
                continue

            last_modified = getattr(details, "last_modified", None)
            updated_at = ""
            if last_modified:
                updated_at = last_modified.isoformat(sep=" ", timespec="seconds") if hasattr(last_modified, "isoformat") else str(last_modified)

            results.append(
                {
                    "repoId": repo_id,
                    "name": repo_id.split("/")[-1],
                    "type": inferred_type,
                    "downloads": int(getattr(details, "downloads", 0) or 0),
                    "likes": int(getattr(details, "likes", 0) or 0),
                    "pipelineTag": pipeline_tag or "",
                    "updatedAt": updated_at,
                    "tags": tags[:6],
                    "ggufFiles": gguf_files[:8],
                }
            )

            if len(results) >= limit:
                break
    except Exception as exc:
        raise RuntimeError(f"HuggingFace search failed: {exc}") from exc

    return results
