from __future__ import annotations

import html
import json
import os
import re
import subprocess
import time
import urllib.error
import urllib.request
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

import psutil
from django.conf import settings


@dataclass
class ArtifactDraft:
    name: str
    language: str
    content: str
    file_type: str = "text"
    disk_path: str = ""


@dataclass
class ResponseDraft:
    content: str
    thinking: str = ""
    files: list[ArtifactDraft] = field(default_factory=list)
    test_passed: bool | None = None
    test_output: str = ""

    @property
    def tokens(self) -> int:
        return max(1, len(self.content.split()) + sum(len(f.content.split()) for f in self.files))


def safe_filename(value: str, fallback: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "_", value).strip("._")
    return cleaned[:80] or fallback


def wants_image(prompt: str) -> bool:
    text = prompt.lower()
    markers = ["/imagine", "создай карт", "сгенерируй карт", "нарисуй", "image", "photo", "picture"]
    return any(marker in text for marker in markers)


def wants_file(prompt: str) -> bool:
    text = prompt.lower()
    markers = [
        "создай файл",
        "сгенерируй файл",
        "write file",
        "create file",
        "напиши код",
        "generate code",
        ".py",
        ".ts",
        ".tsx",
        ".js",
        ".html",
        ".css",
    ]
    return any(marker in text for marker in markers)


def infer_file(prompt: str) -> tuple[str, str]:
    text = prompt.lower()
    explicit = re.search(r"([\w.-]+\.(py|tsx|ts|js|html|css|json|md|txt))", prompt, re.IGNORECASE)
    if explicit:
        name = safe_filename(explicit.group(1), "generated.txt")
        ext = name.rsplit(".", 1)[-1].lower()
    elif "react" in text or "next" in text or "tsx" in text:
        name, ext = "GeneratedWidget.tsx", "tsx"
    elif "html" in text or "сайт" in text:
        name, ext = "index.html", "html"
    elif "css" in text or "style" in text:
        name, ext = "styles.css", "css"
    elif "javascript" in text or "node" in text:
        name, ext = "script.js", "js"
    elif "markdown" in text or "readme" in text:
        name, ext = "README.md", "md"
    else:
        name, ext = "generated_task.py", "py"

    language = {
        "py": "python",
        "tsx": "tsx",
        "ts": "typescript",
        "js": "javascript",
        "html": "html",
        "css": "css",
        "json": "json",
        "md": "markdown",
        "txt": "text",
    }.get(ext, "text")
    return name, language


def generated_dir(kind: str) -> Path:
    path = Path(settings.TTD_GENERATED_DIR) / kind
    path.mkdir(parents=True, exist_ok=True)
    return path


def build_code(prompt: str, name: str, language: str) -> str:
    title = prompt.strip()[:120] or "Generated task"
    if language == "python":
        return f'''"""
Generated by Time To Deny.
Task: {title}
"""


def solve(input_text: str = "") -> str:
    """Return a deterministic response for the requested task."""
    cleaned = input_text.strip()
    if not cleaned:
        return "TTD generated file is ready."
    return f"Processed: {{cleaned}}"


def main() -> None:
    print(solve())


if __name__ == "__main__":
    main()
'''
    if language in {"typescript", "tsx"}:
        return """import React from 'react';

type Props = {
  title?: string;
};

export default function GeneratedWidget({ title = 'Time To Deny' }: Props) {
  return (
    <section className="rounded border border-cyan-400/30 bg-black p-4 text-cyan-100">
      <h2 className="text-sm font-bold tracking-wider">{title}</h2>
      <p className="mt-2 text-xs text-cyan-200/80">
        Generated component scaffold. Wire real data through props before shipping.
      </p>
    </section>
  );
}
"""
    if language == "javascript":
        return """export function runTask(input = '') {
  const value = String(input).trim();
  return value ? `Processed: ${value}` : 'TTD generated file is ready.';
}

console.log(runTask(process.argv.slice(2).join(' ')));
"""
    if language == "html":
        escaped = html.escape(title)
        return f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Time To Deny Generated Page</title>
    <style>
      body {{ margin: 0; background: #050607; color: #d7fff2; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }}
      main {{ min-height: 100vh; display: grid; place-items: center; padding: 24px; }}
      section {{ border: 1px solid rgba(0, 255, 136, .35); padding: 24px; max-width: 720px; }}
    </style>
  </head>
  <body>
    <main>
      <section>
        <h1>Time To Deny</h1>
        <p>{escaped}</p>
      </section>
    </main>
  </body>
</html>
"""
    if language == "css":
        return """:root {
  color-scheme: dark;
  --ttd-bg: #050607;
  --ttd-text: #d7fff2;
  --ttd-accent: #00ff88;
}

.ttd-generated {
  background: var(--ttd-bg);
  color: var(--ttd-text);
  border: 1px solid color-mix(in srgb, var(--ttd-accent), transparent 60%);
  padding: 1rem;
}
"""
    return f"Generated file for task:\n{title}\n"


def test_generated_file(path: Path, language: str) -> tuple[bool, str]:
    if language == "python":
        proc = subprocess.run(
            ["python3", "-m", "py_compile", str(path)],
            capture_output=True,
            text=True,
            timeout=20,
        )
        if proc.returncode == 0:
            return True, "python -m py_compile: OK"
        return False, (proc.stderr or proc.stdout or "py_compile failed").strip()

    if language in {"javascript", "typescript", "tsx"}:
        return True, "Static generation OK. Runtime test skipped because Node.js is optional for backend tests."

    if language == "html":
        content = path.read_text(encoding="utf-8")
        passed = "<html" in content.lower() and "</html>" in content.lower()
        return passed, "HTML smoke check: OK" if passed else "HTML smoke check failed"

    return True, "File write smoke check: OK"


def create_code_artifact(prompt: str) -> tuple[ArtifactDraft, bool, str]:
    name, language = infer_file(prompt)
    content = build_code(prompt, name, language)
    disk_name = f"{uuid.uuid4().hex}_{safe_filename(name, 'generated.txt')}"
    disk_path = generated_dir("files") / disk_name
    disk_path.write_text(content, encoding="utf-8")
    passed, output = test_generated_file(disk_path, language)
    return ArtifactDraft(name=name, language=language, content=content, file_type="code", disk_path=str(disk_path)), passed, output


def create_image_artifact(prompt: str, public_url: str) -> ArtifactDraft:
    image_prompt = prompt.replace("/imagine", "", 1).strip() or "Time To Deny generated image"
    safe_prompt = html.escape(image_prompt[:220])
    disk_name = f"{uuid.uuid4().hex}_ttd_image.svg"
    disk_path = generated_dir("images") / disk_name
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="640" viewBox="0 0 1024 640">
  <defs>
    <linearGradient id="bg" x1="0" x2="1" y1="0" y2="1">
      <stop offset="0" stop-color="#050607"/>
      <stop offset="0.48" stop-color="#071f22"/>
      <stop offset="1" stop-color="#170b24"/>
    </linearGradient>
    <filter id="glow"><feGaussianBlur stdDeviation="6" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
  </defs>
  <rect width="1024" height="640" fill="url(#bg)"/>
  <g opacity="0.28">
    <path d="M0 120 H1024 M0 220 H1024 M0 320 H1024 M0 420 H1024 M0 520 H1024" stroke="#00ff88"/>
    <path d="M128 0 V640 M256 0 V640 M384 0 V640 M512 0 V640 M640 0 V640 M768 0 V640 M896 0 V640" stroke="#00ccff"/>
  </g>
  <circle cx="740" cy="210" r="130" fill="#aa88ff" opacity="0.18" filter="url(#glow)"/>
  <circle cx="300" cy="380" r="170" fill="#00ff88" opacity="0.12" filter="url(#glow)"/>
  <text x="64" y="96" fill="#00ff88" font-family="monospace" font-size="34" font-weight="700">TIME TO DENY</text>
  <text x="64" y="148" fill="#d7fff2" font-family="monospace" font-size="20">generated image placeholder</text>
  <foreignObject x="64" y="210" width="880" height="260">
    <div xmlns="http://www.w3.org/1999/xhtml" style="font: 28px monospace; color: #d7fff2; line-height: 1.35;">
      {safe_prompt}
    </div>
  </foreignObject>
</svg>
"""
    disk_path.write_text(svg, encoding="utf-8")
    return ArtifactDraft(name="ttd_generated_image.svg", language="svg", content=f"{public_url}{disk_name}", file_type="image_url", disk_path=str(disk_path))


def mock_text_response(prompt: str, mode: str, model_name: str, attachment_count: int = 0) -> str:
    attachment_line = ""
    if attachment_count:
        attachment_line = f"\n\nЯ получил вложения: {attachment_count}. Их содержимое сохранено вместе с сообщением."
    mode_line = "Expert mode включен: отвечаю подробнее и с проверками." if mode == "expert" else "Instant mode: коротко и по делу."
    return (
        f"{mode_line}\n\n"
        f"Модель `{model_name}` приняла запрос и backend реально записал его в базу. "
        "Если подключить `TTD_MODEL_BACKEND=llamacpp`, этот же поток пойдет через локальный `llama-server`. "
        "Сейчас mock-backend закрывает интерфейс, хранение, стриминг и служебные действия без ожидания тяжелых весов."
        f"{attachment_line}\n\n"
        f"Запрос: {prompt.strip() or '[empty]'}"
    )


def build_local_draft(prompt: str, mode: str, model_name: str, public_image_base: str, attachment_count: int = 0) -> ResponseDraft:
    thinking = ""
    if mode == "expert":
        thinking = "Analyzing request...\nChecking whether files or images are needed...\nPreparing persistent artifacts and tests..."

    if wants_image(prompt):
        file = create_image_artifact(prompt, public_image_base)
        return ResponseDraft(
            content="Сгенерировал изображение и приложил его к ответу.",
            thinking=thinking,
            files=[file],
            test_passed=True,
            test_output="Image artifact written to media/generated/images",
        )

    if wants_file(prompt):
        file, passed, output = create_code_artifact(prompt)
        return ResponseDraft(
            content=f"Создал файл `{file.name}`. Содержимое показано ниже, тест/проверка уже выполнены.",
            thinking=thinking,
            files=[file],
            test_passed=passed,
            test_output=output,
        )

    return ResponseDraft(content=mock_text_response(prompt, mode, model_name, attachment_count), thinking=thinking)


def chunk_text(text: str, size: int = 16) -> Iterable[str]:
    for idx in range(0, len(text), size):
        yield text[idx : idx + size]


def llama_cpp_prompt(prompt: str, mode: str, model_name: str, system_prompt: str = "") -> str:
    system = system_prompt.strip() or (
        "You are Time To Deny, a local AI assistant powered by llama.cpp. "
        "Answer clearly, stream useful output, and prefer runnable code when asked."
    )
    if mode == "expert":
        system += "\nUse careful reasoning internally, then provide a direct final answer."
    else:
        system += "\nAnswer directly and keep latency low."
    return (
        "<|system|>\n"
        f"{system}\n"
        "<|user|>\n"
        f"{prompt.strip()}\n"
        "<|assistant|>\n"
    )


def stream_llamacpp(prompt: str, mode: str, model_name: str, system_prompt: str = "") -> Iterable[str]:
    payload = {
        "prompt": llama_cpp_prompt(prompt, mode, model_name, system_prompt),
        "stream": True,
        "temperature": 0.2 if mode == "expert" else 0.5,
        "n_predict": settings.TTD_LLAMA_CPP_N_PREDICT,
        "cache_prompt": True,
        "stop": ["<|user|>", "<|system|>", "</s>"],
    }
    req = urllib.request.Request(
        f"{settings.TTD_LLAMA_CPP_URL.rstrip('/')}/completion",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=settings.TTD_REQUEST_TIMEOUT_SECONDS) as response:
            for raw in response:
                if not raw:
                    continue
                line = raw.decode("utf-8").strip()
                if not line or line.startswith(":"):
                    continue
                if line.startswith("data:"):
                    line = line[5:].strip()
                if line == "[DONE]":
                    break
                item = json.loads(line)
                token = item.get("content") or item.get("response") or ""
                if token:
                    yield token
                if item.get("stop") or item.get("done"):
                    break
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
        yield f"\n\n[llama.cpp backend unavailable: {exc}. Start llama-server or switch TTD_MODEL_BACKEND=mock for UI-only dev.]"


def system_snapshot(interval: str) -> dict:
    cpu = psutil.cpu_percent(interval=0.1)
    mem = psutil.virtual_memory()
    current = {
        "cpu": round(cpu, 1),
        "ram": round(mem.percent, 1),
        "gpu": 0,
        "vram": 0,
        "temp": 0,
        "fanRpm": 0,
        "totalVram": "-",
        "usedVram": "-",
        "totalRam": f"{mem.total / (1024 ** 3):.1f}GB",
        "usedRam": f"{mem.used / (1024 ** 3):.1f}GB",
    }

    points = {"1min": 60, "30min": 30, "1hr": 60, "1day": 24, "1week": 7}.get(interval, 30)
    data = []
    for i in range(points):
        wave = (i % 10) * 1.7
        data.append(
            {
                "t": label_for_interval(interval, i),
                "cpu": max(0, min(100, cpu + wave - 8)),
                "ram": max(0, min(100, mem.percent + (i % 7) - 3)),
                "gpu": 0,
                "vram": 0,
                "tps": max(0, min(80, 12 + (i % 12) * 2.5)),
            }
        )

    processes = []
    for proc in psutil.process_iter(["pid", "name", "cpu_percent", "num_threads", "create_time"]):
        try:
            name = proc.info.get("name") or ""
            lowered = name.lower()
            if not any(marker in lowered for marker in ["python", "llama", "node", "next"]):
                continue
            uptime = max(0, time.time() - float(proc.info.get("create_time") or time.time()))
            processes.append(
                {
                    "id": f"proc-{proc.info['pid']}",
                    "name": name,
                    "pid": proc.info["pid"],
                    "status": "active",
                    "vram": "-",
                    "cpu": f"{proc.info.get('cpu_percent') or 0:.1f}%",
                    "threads": proc.info.get("num_threads") or 0,
                    "uptime": format_uptime(uptime),
                }
            )
        except (psutil.NoSuchProcess, psutil.AccessDenied, ValueError):
            continue

    return {"current": current, "history": data, "processes": processes[:24], "system": system_info()}


def label_for_interval(interval: str, index: int) -> str:
    if interval == "1min":
        return f"{index}s"
    if interval in {"30min", "1hr"}:
        return f"{index}m"
    if interval == "1day":
        return f"{index}:00"
    return ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"][index % 7]


def format_uptime(seconds: float) -> str:
    minutes = int(seconds // 60)
    hours = minutes // 60
    minutes = minutes % 60
    if hours:
        return f"{hours}h {minutes}m"
    return f"{minutes}m"


def system_info() -> list[dict[str, str]]:
    mem = psutil.virtual_memory()
    return [
        {"label": "CPU", "value": os.uname().machine if hasattr(os, "uname") else "unknown"},
        {"label": "RAM", "value": f"{mem.total / (1024 ** 3):.1f}GB"},
        {"label": "Python", "value": os.sys.version.split()[0]},
        {"label": "Model backend", "value": settings.TTD_MODEL_BACKEND},
        {"label": "llama.cpp URL", "value": settings.TTD_LLAMA_CPP_URL},
        {"label": "Model dir", "value": str(settings.TTD_MODEL_DIR)},
    ]


def infer_hf_model_type(repo_id: str, tags: list[str], pipeline_tag: str | None = None) -> str:
    haystack = " ".join([repo_id, *tags, pipeline_tag or ""]).lower()
    code_markers = ("coder", "code", "programming", "fill-mask-code")
    vision_markers = ("vision", "image", "diffusion", "stable-diffusion", "sdxl", "flux", "clip", "siglip")

    if any(marker in haystack for marker in code_markers):
        return "code"
    if any(marker in haystack for marker in vision_markers):
        return "vision"
    return "text"


def search_huggingface_models(query: str, model_type: str = "", limit: int = 8) -> list[dict[str, Any]]:
    try:
        from huggingface_hub import HfApi
    except ImportError as exc:
        raise RuntimeError("huggingface_hub is not installed on the backend") from exc

    api = HfApi()
    normalized_query = (query or "").strip()
    normalized_type = model_type if model_type in {"text", "vision", "code"} else ""
    fetch_limit = max(limit * 5, 24)
    seen: set[str] = set()
    results: list[dict[str, Any]] = []
    search_term = f"{normalized_query} GGUF".strip() if normalized_query else "gguf"

    try:
        iterator = api.list_models(search=search_term, limit=fetch_limit)
        for item in iterator:
            repo_id = getattr(item, "id", None) or getattr(item, "modelId", None)
            if not repo_id or repo_id in seen:
                continue
            seen.add(repo_id)

            try:
                details = api.model_info(repo_id)
            except Exception:
                continue

            siblings = getattr(details, "siblings", None) or []
            gguf_files = sorted(
                {
                    getattr(file, "rfilename", "")
                    for file in siblings
                    if getattr(file, "rfilename", "").lower().endswith(".gguf")
                }
            )
            if not gguf_files:
                continue

            tags = list(getattr(details, "tags", None) or getattr(item, "tags", None) or [])
            pipeline_tag = getattr(details, "pipeline_tag", None) or getattr(item, "pipeline_tag", None)
            inferred_type = infer_hf_model_type(repo_id, tags, pipeline_tag)
            if normalized_type and inferred_type != normalized_type:
                continue

            last_modified = getattr(details, "last_modified", None)
            updated_at = ""
            if last_modified:
                updated_at = last_modified.isoformat(sep=" ", timespec="seconds") if hasattr(last_modified, "isoformat") else str(last_modified)

            results.append(
                {
                    "repoId": repo_id,
                    "name": repo_id.split("/")[-1],
                    "type": inferred_type,
                    "downloads": int(getattr(details, "downloads", 0) or 0),
                    "likes": int(getattr(details, "likes", 0) or 0),
                    "pipelineTag": pipeline_tag or "",
                    "updatedAt": updated_at,
                    "tags": tags[:6],
                    "ggufFiles": gguf_files[:8],
                }
            )

            if len(results) >= limit:
                break
    except Exception as exc:
        raise RuntimeError(f"HuggingFace search failed: {exc}") from exc

    return results
